### ISSUE TITLE
Error when selecting 'All Available Datasets' 

### ISSUE THREAD

**Issue by jrmartin** [VirtualFlyBrain/VFB2#228]
Steps to reproduce the problem: 
1) Click on 'Datasets' option in top left corner menu. 
2) Select 'All Available Datasets'

![Screenshot from 2020-05-15 12-12-49](https://user-images.githubusercontent.com/4562825/82087850-c198ac80-96a5-11ea-83fd-880334ba8854.png)

Error Information:

Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at QueryLinkArrayComponent.render (http://localhost:8081/org.geppetto.frontend/geppetto/build/main.bundle.js:28359:46)
    at finishClassComponent (http://localhost:8081/org.geppetto.frontend/geppetto/build/common.bundle.js:43440:31)
    at updateClassComponent (http://localhost:8081/org.geppetto.frontend/geppetto/build/common.bundle.js:43390:24)
    at beginWork (http://localhost:8081/org.geppetto.frontend/geppetto/build/common.bundle.js:44900:16)
    at HTMLUnknownElement.callCallback (http://localhost:8081/org.geppetto.frontend/geppetto/build/common.bundle.js:26468:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8081/org.geppetto.frontend/geppetto/build/common.bundle.js:26517:16)
    at invokeGuardedCallback (http://localhost:8081/org.geppetto.frontend/geppetto/build/common.bundle.js:26572:31)
    at beginWork$1 (http://localhost:8081/org.geppetto.frontend/geppetto/build/common.bundle.js:49483:7)
    at performUnitOfWork (http://localhost:8081/org.geppetto.frontend/geppetto/build/common.bundle.js:48437:12)
    at workLoopSync (http://localhost:8081/org.geppetto.frontend/geppetto/build/common.bundle.js:48410:22)

```diff
  Loading....
  
 %c %c %c PixiJS 4.8.9 - ✰ WebGL ✰  %c  %c  http://www.pixijs.com/  %c %c ♥%c♥%c♥ 


background: %23ff66a5

**Comment by Robbie1977** [comment]
@jrmartin this may have been a temporary data (pdb-dev) issue which should now be resolved. Can you still get this error? 
I can't replicate but was a loading issues with pdb-dev yesterday.
