### ISSUE TITLE
Issue when first opening graph when a term that doesn't match supertypes for query is selected.

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB2#280]
Steps to reproduce the problem: 

Please fill the below with the necessary steps to reproduce the problem

open http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBrf0212889&i=VFB_00101567 and select a publication and then the graph tab or sync the graph with a publication selected.

Error Information:

this.querySelection.label is not a function

TypeError: this.querySelection.label is not a function
    at n.value (http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:289:1514169)
    at n.value (http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:289:1515466)
    at La (http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:69876)
    at Fa (http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:69671)
    at gl (http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:105470)
    at us (http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:96717)
    at ls (http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:96642)
    at Zl (http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:93672)
    at http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:45314
    at t.unstable_runWithPriority (http://v2a.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:54:3844)

```diff
+ Host for MessageSocket to connect: wss://v2a.virtualflybrain.org/org.geppetto.frontend/GeppettoServlet
+ %c WebSocket Status - Opened 
background: %23444; color: #bada55
+ 
 %c %c %c PixiJS 4.8.9 - &#10032; WebGL &#10032;  %c  %c  http://www.pixijs.com/  %c %c &#9829;%c&#9829;%c&#9829; 


background: #ff66a5; padding:5px 0;
background: #ff66a5; padding:5px 0;
color: #ff66a5; background: #030307; padding:5px 0;
background: #ff66a5; padding:5px 0;
background: #ffc3dc; padding:5px 0;
background: #ff66a5; padding:5px 0;
color: #ff2424; background: #fff; padding:5px 0;
color: #ff2424; background: #fff; padding:5px 0;
color: #ff2424; background: #fff; padding:5px 0;
+ Loading 171 slices/tiles...
- TypeError: this.querySelection.label is not a function
+ USER: 84.70.215.173  London, EN, United Kingdom
```

**Comment by Robbie1977** [comment]
FYI this is an issue with any query that returns no results.

**Comment by Robbie1977** [comment]
Query modified to make this rarer but still needs a fix for no results
