### ISSUE TITLE
Posting error that happened

### ISSUE THREAD

**Issue by TrentBrick** [VirtualFlyBrain/VFB2#318]
Steps to reproduce the problem: 

Please fill the below with the necessary steps to reproduce the problem

Error Information:

this.props.instanceOnFocus.getParent is not a function

TypeError: this.props.instanceOnFocus.getParent is not a function
    at n.value (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:294:653876)
    at il (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:83470)
    at ds (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:101245)
    at t.unstable_runWithPriority (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:54:3844)
    at Bo (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:45023)
    at ps (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:97717)
    at Zl (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:93871)
    at https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:45314
    at t.unstable_runWithPriority (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:54:3844)
    at Bo (https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:45023)

```diff
+ Host for MessageSocket to connect: wss://v2.virtualflybrain.org/org.geppetto.frontend/GeppettoServlet
+ %c WebSocket Status - Open connection error 
background: %23000; color: red
+ WebSocket Status - retry in 5000ms
[object CloseEvent]
+ %c WebSocket Status - reconnecting... 
background: #444; color: #bada55
+ %c WebSocket Status - Opened 
background: #444; color: #bada55
- TypeError: this.props.instanceOnFocus.getParent is not a function
```

**Comment by TrentBrick** [comment]
Nope everything is working great now upon reloading. 

This was the first time I have ever tried the site. None of the viewers were displaying anything and then clicking around this error got thrown.
